### ISSUE TITLE
Hey, I would like to get a few acconts

### ISSUE THREAD

**Issue by sneedgers** [Zaydo123/twitchgen#1]
Could I buy some for 0.02Cent-per account in bulk ?

I offer for 200 accounts 2$ for example ! <3

**Comment by Zaydo123** [comment]
I can't but my friend can https://destruction.sellix.io/product/6314714d43bca

**Comment by sneedgers** [comment]
> I can't but my friend can https://destruction.sellix.io/product/6314714d43bca

Looking for tokens themselves. 
I am behind the TwitchDoBetter hate raids!
